server:
    port: 4006
    error:
        include-message: always


spring:
    application:
        name: api
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true #
                    lower-case-service-id: true
                
management:
    endpoint:
        gateway:
            enabled: true
    endpoints:
        web:
            exposure:
                include: '*'
logging:
    level:
        org.springframework.cloud.gateway: DEBUG


main:
    allow-bean-definition-overriding: true

eureka:
    client:
        serviceUrl:
            defaultZone: http://192.168.120.186:8761/eureka/ ## URL du serveur Eureka
        fetch-registry: true # Récupérer la liste des services
        register-with-eureka: true # S'enregistrer auprès du serveur
    instance:
        prefer-ip-address: true 

yowyob:
    openapi:
        prod-url: http://localhost:4000
        dev-url: http://localhost:4000 
        url: http://localhost:5000

springdoc:
    api-docs:
        path: /v3/api-docs # OpenAPI JSON path
    swagger-ui:
        enabled: true
        path: /swagger-ui.html # Swagger UI path
